- name: Wait for SSH to be available
  hosts: localhost
  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      with_items: "{{ hosts }}"
