name: Terraform apply

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  #  inputs:
  #    environment:
  #      description: 'Environment to deploy to'
  #      required: true
  #      default: 'production'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.1
      with:
        terraform_version: v1.9.0

    - name: Set up SSH keys
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.SERVICE_ACCOUNT_KEY_FILE }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519.pub
        echo "$SERVICE_ACCOUNT_KEY_FILE" > ~/.ssh/authorized_key.json
        chmod 600 ~/.ssh/authorized_key.json
 #   - name: Terraform fmt
 #     run: terraform fmt -check=true

 #   - name: Terraform validate
 #     run: terraform validate

    - name: Initialize Terraform
      env:
        TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
        TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
#        TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
        TF_VAR_service_account_key_file: ~/.ssh/authorized_key.json
#        TF_VAR_service_account_key_file: ${{ secrets.SERVICE_ACCOUNT_KEY_FILE }}
        TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
      run: terraform init

    - name: Apply Terraform
      env:
        TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
        TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
#        TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
        TF_VAR_service_account_key_file: ~/.ssh/authorized_key.json
#        TF_VAR_service_account_key_file: ${{ secrets.SERVICE_ACCOUNT_KEY_FILE }}
        TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
      run: terraform apply -auto-approve

    - name: Wait for SSH
      run: |
        for host in $(terraform output -json | jq -r '.k8s_master_ips.value[]'); do
          ansible -m wait_for -a "host=$host port=22 delay=10 timeout=300" localhost
        done
        for host in $(terraform output -json | jq -r '.k8s_worker_ips.value[]'); do
          ansible -m wait_for -a "host=$host port=22 delay=10 timeout=300" localhost
        done

    - name: Clean up on failure
      if: failure()
      env:
        TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
        TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_service_account_key_file: ~/.ssh/authorized_key.json
        TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
      run: terraform destroy -auto-approve
