name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: v1.9.0

      - name: Set up SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.SERVICE_ACCOUNT_KEY_FILE }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519.pub
          echo "$SERVICE_ACCOUNT_KEY_FILE" > ~/.ssh/authorized_key.json
          chmod 600 ~/.ssh/authorized_key.json

      - name: Initialize Terraform
        env:
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          TF_VAR_service_account_key_file_path: ~/.ssh/authorized_key.json
          TF_VAR_ssh_private_key_path: ~/.ssh/id_ed25519
        run: terraform init

      - name: Apply Terraform
        env:
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          TF_VAR_service_account_key_file_path: ~/.ssh/authorized_key.json
          TF_VAR_ssh_private_key_path: ~/.ssh/id_ed25519
        run: terraform apply -auto-approve

      - name: Generate hosts.yaml
        env:
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          TF_VAR_service_account_key_file_path: ~/.ssh/authorized_key.json
          TF_VAR_ssh_private_key_path: ~/.ssh/id_ed25519
        run: |
          terraform output -json > terraform_output.json
          python3 generate_hosts.py

      - name: Wait for SSH to be available
        run: |
          for host in $(terraform output -json master_external_ips | jq -r '.[]'); do
            start_time=$(date +%s)
            timeout=180
            while ! ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@$host "echo SSH connection successful"; do
              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))
              if [ $elapsed_time -ge $timeout ]; then
                echo "Timeout waiting for SSH to be available on $host"
                exit 1
              fi
              echo "Waiting for SSH to be available on $host..."
              sleep 10
            done
          done

      - name: Test sudo access
        run: |
          for host in $(terraform output -json master_external_ips | jq -r '.[]'); do
            start_time=$(date +%s)
            timeout=60
            while ! ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@$host "sudo -n true"; do
              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))
              if [ $elapsed_time -ge $timeout ]; then
                echo "Timeout waiting for sudo access on $host"
                exit 1
              fi
              echo "Waiting for sudo access on $host..."
              sleep 10
            done
          done

      - name: Run Docker container and setup Kubespray
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          docker run -v ~/.ssh/id_ed25519:/root/.ssh/id_ed25519 -v $(pwd):/workspace python /bin/bash -c "
            apt-get update && apt-get install -y git ansible &&
            git clone https://github.com/kubernetes-sigs/kubespray.git /root/kubespray &&
            cd /root/kubespray &&
            pip3 install -r requirements.txt &&
            cp -rfp /root/kubespray/inventory/sample /root/kubespray/inventory/mycluster &&
            cp /workspace/hosts.yaml /root/kubespray/inventory/mycluster/hosts.yaml &&
            cat /root/kubespray/inventory/mycluster/hosts.yaml &&
            ansible-playbook -i /root/kubespray/inventory/mycluster/hosts.yaml /root/kubespray/cluster.yml -b -vvv
          "

      - name: Destroy Terraform Infrastructure
        if: always()
        env:
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_yc_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          TF_VAR_service_account_key_file_path: ~/.ssh/authorized_key.json
          TF_VAR_ssh_private_key_path: ~/.ssh/id_ed25519
        run: terraform destroy -auto-approve
